### ISSUE TITLE
Reverse an array

### ISSUE THREAD

**Issue by tarushi0503** [tarushi0503/Java-DSA#15]
Write a program to reverse array

**Comment by siddhesh-desai** [comment]
@tarushi0503 please assign me

**Comment by theshoonyam** [comment]
Can you assign this issue to me?

**Comment by tarushi0503** [comment]
Assigned @aadi-raj @siddhesh-desai

**Comment by vaibhv232** [comment]
hello ma'am assign me this issue

**Comment by siddhesh-desai** [comment]
Solved at #20
