### ISSUE TITLE
Minimum and maximum element in an array

### ISSUE THREAD

**Issue by tarushi0503** [tarushi0503/Java-DSA#21]
Write a java program to find the minimum and maximum element in an array

**Comment by ishaan010** [comment]
Hi @tarushi0503  I am ezpie. Can I take This issue? And where should I put the file?

**Comment by shruti-2412** [comment]
Can I do this?

**Comment by shruti-2412** [comment]
Please assign it to me

**Comment by idrismusa4** [comment]
Assign to me please @tarushi0503

**Comment by amanaggarwal06** [comment]
Hey, please assign it to me.
I want to contribute.
