### ISSUE TITLE
Merger Sort

### ISSUE THREAD

**Issue by tarushi0503** [tarushi0503/Java-DSA#24]
Write a java program to implement merge sort

**Comment by SainathPoojary** [comment]
Hey @tarushi0503, I want to work on this Please assign it to me.

**Comment by SainathPoojary** [comment]
Hey @tarushi0503, I have raised a PR. Please review it and do let me know if you need any changes

**Comment by satyam2k3** [comment]
can u assign this to me?

**Comment by tarushi0503** [comment]
Assigned @SainathPoojary @satyam2k3
