### ISSUE TITLE
Linear search

### ISSUE THREAD

**Issue by tarushi0503** [tarushi0503/Java-DSA#3]
Write a Java program for linear search

**Comment by theshoonyam** [comment]
Can you please assign this issue to me?

**Comment by sonal3yadav** [comment]
@tarushi0503 assign me

**Comment by dhanya017** [comment]
@tarushi0503 plz assign me

**Comment by tarushi0503** [comment]
Assigned @aadi-raj @dhanya017 @sonal3yadav
