### ISSUE TITLE
Bubble Sort

### ISSUE THREAD

**Issue by tarushi0503** [tarushi0503/Java-DSA#4]
Write a Java program to implement bubble sort

**Comment by Visbhavesh** [comment]
hey @tarushi0503  assign me

**Comment by sonal3yadav** [comment]
@tarushi0503 assign me

**Comment by tarushi0503** [comment]
Assigned @Visbhavesh @sonal3yadav

**Comment by dhanya017** [comment]
@tarushi0503 assign me
