### ISSUE TITLE
Insertion sort

### ISSUE THREAD

**Issue by tarushi0503** [tarushi0503/Java-DSA#7]
Write a java program to implement insertion sort

**Comment by siddhesh-desai** [comment]
Hello @tarushi0503, I would like to contribute in it. Please assign me.

**Comment by sonal3yadav** [comment]
assign me @tarushi0503

**Comment by theshoonyam** [comment]
Hi, I would like to contribute.

**Comment by tarushi0503** [comment]
Assigned @sonal3yadav @aadi-raj @siddhesh-desai
